spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:sa;MODE=MySQL;INIT=CREATE SCHEMA IF NOT EXISTS sa
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
  sql:
    init:
      enabled: true
hibernate:
  hbm2ddl:
    auto: create

